In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("C:\\Users\\Lenovo\\Downloads\\archive (9)\\appendix.csv")
data

,Institution,Course Number,Launch Date,Course Title,Instructors,Course Subject,Year,Honor Code Certificates,Participants (Course Content Accessed),Audited (> 50% Course Content Accessed),...,% Certified of > 50% Course Content Accessed,% Played Video,% Posted in Forum,% Grade Higher Than Zero,Total Course Hours (Thousands),Median Hours for Certification,Median Age,% Male,% Female,% Bachelor's Degree or Higher
0,MITx,6.002x,09/05/2012,Circuits and Electronics,Khurram Afridi,"Science, Technology, Engineering, and Mathematics",1,1,36105,5431,...,54.98,83.2,8.17,28.97,418.94,64.45,26.0,88.28,11.72,60.68
1,MITx,6.00x,09/26/2012,Introduction to Computer Science and Programming,"Eric Grimson, John Guttag, Chris Terman",Computer Science,1,1,62709,8949,...,64.05,89.14,14.38,39.50,884.04,78.53,28.0,83.50,16.50,63.04
2,MITx,3.091x,10/09/2012,Introduction to Solid State Chemistry,Michael Cima,"Science, Technology, Engineering, and Mathematics",1,1,16663,2855,...,72.85,87.49,14.42,34.89,227.55,61.28,27.0,70.32,29.68,58.76
3,HarvardX,CS50x,10/15/2012,Introduction to Computer Science,"David Malan, Nate Hardison, Rob Bowden, Tommy ...",Computer Science,1,1,129400,12888,...,11.11,0,0.00,1.11,220.90,0.00,28.0,80.02,19.98,58.78
4,HarvardX,PH207x,10/15/2012,Health in Numbers: Quantitative Methods in Cli...,"Earl Francis Cook, Marcello Pagano","Government, Health, and Social Science",1,1,52521,10729,...,47.12,77.45,15.98,32.52,804.41,76.10,32.0,56.78,43.22,88.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
285,HarvardX,MUS24.4x,07/21/2016,First Nights: Symphonie Fantastique,Tom Kelly,"Humanities, History, Design, Religion, and Edu...",4,0,615,305,...,6.56,80.81,8.78,3.25,1.71,5.93,38.0,56.82,43.18,74.66
286,HarvardX,GSE4x,07/25/2016,Introduction to Family Engagement in Education,Karen Mapp,"Humanities, History, Design, Religion, and Edu...",4,0,2871,267,...,7.49,70.11,0.00,0.70,4.26,11.33,34.0,25.24,74.76,82.31
287,MITx,6.302.0x,08/01/2016,Introduction to Control System Design,"Jacob White, Joe Steinmeyer","Science, Technology, Engineering, and Mathematics",4,0,3937,974,...,5.03,12.27,4.72,8.23,15.62,58.50,24.0,91.17,8.83,61.32
288,MITx,6.302.1x,08/01/2016,Introduction to State Space Control,"Jacob White, Joe Steinmeyer","Science, Technology, Engineering, and Mathematics",4,0,1431,208,...,3.85,0,3.84,5.73,3.22,62.38,25.0,93.44,6.56,72.31
289,MITx,3.15.3x,08/03/2016,Magnetic Materials and Devices,Caroline Ross,"Science, Technology, Engineering, and Mathematics",4,0,1294,364,...,10.44,49.92,4.40,14.30,6.87,40.59,25.0,85.95,14.05,65.78

In [3]:
data.columns

Index(['Institution', 'Course Number', 'Launch Date', 'Course Title',
       'Instructors', 'Course Subject', 'Year', 'Honor Code Certificates',
       'Participants (Course Content Accessed)',
       'Audited (> 50% Course Content Accessed)', 'Certified', '% Audited',
       '% Certified', '% Certified of > 50% Course Content Accessed',
       '% Played Video', '% Posted in Forum', '% Grade Higher Than Zero',
       'Total Course Hours (Thousands)', 'Median Hours for Certification',
       'Median Age', '% Male', '% Female', '% Bachelor's Degree or Higher'],
      dtype='object')

In [4]:
columns_to_drop = ["Launch Date", "Participants (Course Content Accessed)", "Audited (> 50% Course Content Accessed)", "% Male", "% Female", "Median Hours for Certification", "Course Number", "Year", "Honor Code Certificates", "Total Course Hours (Thousands)"]


columns_to_drop += data.columns[10:17].tolist()



courses = data.drop(columns=columns_to_drop)

courses.drop(["Median Age", "% Bachelor's Degree or Higher"], axis=1, inplace=True)

In [5]:
courses.columns

Index(['Institution', 'Course Title', 'Instructors', 'Course Subject'], dtype='object')

In [6]:
courses = courses.dropna()

In [7]:
tokenz = lambda x:x.split()
courses["Instructors"] = courses["Instructors"].apply(lambda x:x.split(","))
courses["Course Subject"] = courses["Course Subject"].apply(tokenz)

In [8]:
courses

,Institution,Course Title,Instructors,Course Subject
0,MITx,Circuits and Electronics,[Khurram Afridi],"[Science,, Technology,, Engineering,, and, Mat..."
1,MITx,Introduction to Computer Science and Programming,"[Eric Grimson, John Guttag, Chris Terman]","[Computer, Science]"
2,MITx,Introduction to Solid State Chemistry,[Michael Cima],"[Science,, Technology,, Engineering,, and, Mat..."
3,HarvardX,Introduction to Computer Science,"[David Malan, Nate Hardison, Rob Bowden, To...","[Computer, Science]"
4,HarvardX,Health in Numbers: Quantitative Methods in Cli...,"[Earl Francis Cook, Marcello Pagano]","[Government,, Health,, and, Social, Science]"
...,...,...,...,...
285,HarvardX,First Nights: Symphonie Fantastique,[Tom Kelly],"[Humanities,, History,, Design,, Religion,, an..."
286,HarvardX,Introduction to Family Engagement in Education,[Karen Mapp],"[Humanities,, History,, Design,, Religion,, an..."
287,MITx,Introduction to Control System Design,"[Jacob White, Joe Steinmeyer]","[Science,, Technology,, Engineering,, and, Mat..."
288,MITx,Introduction to State Space Control,"[Jacob White, Joe Steinmeyer]","[Science,, Technology,, Engineering,, and, Mat..."
289,MITx,Magnetic Materials and Devices,[Caroline Ross],"[Science,, Technology,, Engineering,, and, Mat..."

In [9]:
courses["Instructors"]=courses["Instructors"].apply(lambda x: [i.replace(" ", "") for i in x])

In [10]:
courses["tags"] = courses["Course Subject"] + courses["Instructors"]
print(len(courses.iloc[0]["tags"]))

6

In [11]:
def append_string(row):
    return row['tags'] + [row['Institution']]

courses["tags"] = courses.apply(append_string, axis=1)

In [12]:
new_df = courses[["Course Title", "Instructors", "tags"]]

In [13]:
new_df["tags"] = (new_df["tags"].apply(lambda x: " ".join(x)).replace(',', "")).apply(lambda x: x.replace(",", ""))

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_33800\3095689560.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["tags"] = (new_df["tags"].apply(lambda x: " ".join(x)).replace(',', "")).apply(lambda x: x.replace(",", ""))

In [14]:
new_df["tags"]=new_df["tags"].apply(lambda x: x.lower())

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_33800\445237715.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["tags"]=new_df["tags"].apply(lambda x: x.lower())

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer 
tfidf = TfidfVectorizer(max_features=1000, stop_words='english')

In [16]:
import nltk

In [17]:
from nltk.stem.porter import PorterStemmer 

ps = PorterStemmer()

def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [18]:
new_df["tags"] = new_df['tags'].apply(stem)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_33800\3536001088.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["tags"] = new_df['tags'].apply(stem)

In [19]:
path = "C:\\Users\\Lenovo\\Desktop\\practice+projex\\CodeCraft-TM-PAI\\CodeCraft-TM-PAI\\new_df.csv"
new_df.to_csv(path)

In [20]:
vectors =  tfidf.fit_transform(new_df['tags']).toarray()

In [21]:
from sklearn.metrics.pairwise import cosine_similarity

In [22]:
similarity= cosine_similarity(vectors)

In [23]:
def recommend(course):
    course_index = new_df[new_df['Course Title'] == course].index[0]
    course_list = sorted(list(enumerate(similarity[course_index])), key=lambda x: x[1], reverse=True)
    list_ = []
    for i in course_list:
      if new_df.iloc[i[0]]["Course Title"] == course:
         continue
      if len(list(set(list_)))<6:
         list_.append(new_df.iloc[i[0]]["Course Title"])
    #print(f"{type(new_df.iloc[i[0]]['Course Title'])}")
       
    return list(set(list_))

In [24]:
a = recommend("Circuits and Electronics")
display(a)

['Introduction to Solid State Chemistry',
 'Introduction to Biology: Secret of Life',
 'Electronic Materials and Devices',
 'Mastering Quantum Mechanics',
 'Optical Materials and Devices',
 'Electrical, Optical and Magnetic Materials and Devices']

In [1]:
import hashlib

def sha256_hash(text):
    # Encode the text into bytes before hashing
    text_bytes = text.encode('utf-8')
    # Create a new SHA-256 hash object
    sha256_hash_obj = hashlib.sha256()
    # Update the hash object with the bytes
    sha256_hash_obj.update(text_bytes)
    # Get the hexadecimal digest of the hash
    hashed_text = sha256_hash_obj.hexdigest()
    return hashed_text

# Strings to hash
strings = [
    "abefgh",
    "abc",
    "acdefg1",
    "abcde1fg1",
    "cdefg1",
    "abc1efg1",
    "ab1cd1efg1",
    "cefg",
    "abcg1",
    "abcfg1",
    "abcdefg10000",
    "abefg11",
    "abcdefg1119999",
    "abcd987efg1",
    "abcdefg111",
    "abcdefg",
    "abc67defg1111",
    "abcdefg1",
    "abcde898989fg",
    "abcdefg1111"
]

# Hash each string using SHA-256
for text in strings:
    hashed_text = sha256_hash(text)
    print(f"Text: {text}\nHash: {hashed_text}\n")

Text: abefgh
Hash: 81b62790edd6911d80a637e26669b352632cbbe709d4eb647b97a0168c334883

Text: abc
Hash: ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad

Text: acdefg1
Hash: bd172c7c70b28172118900b90e33f0ab370597ab2dbdf8574e7867ac333281e9

Text: abcde1fg1
Hash: 3b3b9dbb72bf413560ae135ae8c1845c5e13167a49c6c1f46f8865e21e422741

Text: cdefg1
Hash: 5c93dd2962cb02f3b5a175aa010a52c7dd8ad19f323dd275e3da7d46813df917

Text: abc1efg1
Hash: 325b2fbe110c51c31256264fed69ba9c7ee7fb6b28f827234adefc00db03ae5c

Text: ab1cd1efg1
Hash: a65e739a1a56d9124a0130c03c28937fd7737070b3965ec6c36155b104cf43a3

Text: cefg
Hash: 22af167233e099b097f3041ea57bde5da0318292037db4b0d953a3bd8818c4c1

Text: abcg1
Hash: 2f41c141f9b2494aea3d17725608e27c61008375298c02723ee262082a19f723

Text: abcfg1
Hash: 3948931db7e4b89fc98e06829801121e8d00878aafdeb87a1f5e6e7f82913430

Text: abcdefg10000
Hash: 23c94648db197dfe7cb7867c548a09735795d3b29281397415b17a51e222d0f8

Text: abefg11
Hash: ddc44668c4618598c69800e6b5d6c971e04c14eec479d8fa5db44aeae5552344

Text: abcdefg1119999
Hash: dcab9b326ac6c6a5e37327fbf100b5aa2ad0e2408e6ebef1766e963f0cb1f796

Text: abcd987efg1
Hash: 7cfee2d4ea1497ea9f334af087f0b0aa9fd41f22be61cbfa13c6999d71ea036f

Text: abcdefg111
Hash: 9837d4831dff630e1d5ccc40fa923cb6217a4f3dedb5e878583589ac3626fc23

Text: abcdefg
Hash: 7d1a54127b222502f5b79b5fb0803061152a44f92b37e23c6527baf665d4da9a

Text: abc67defg1111
Hash: d5f3cac4123a5aa4c7836f618f4a66ca1235bf0fb8d40b48a84f5a3882260e5c

Text: abcdefg1
Hash: ec5acefa44cf8383f4ebaff94b6bfa200a9fdbe92aaf11481907c040c4a11b54

Text: abcde898989fg
Hash: a46d8562019c148ad900ff9c5399eaebdaeec2f63d67e60afaa4cd373f086a26

Text: abcdefg1111
Hash: 7a37eb4d43b8d486053d8cf1925ee064d13b688e0ff1a2c1b2c07af3eb77af49

In [29]:
import numpy as  np

a =  np.array([[1,2,3], [4,5,6], [7,8,10]], dtype=np.double)
b = np.dot(np.linalg.inv(a),a)

b

array([[ 1.00000000e+00,  0.00000000e+00,  2.22044605e-16],
       [ 1.33226763e-15,  1.00000000e+00,  8.88178420e-16],
       [-7.77156117e-16,  0.00000000e+00,  1.00000000e+00]])

NameError: name '__INT__MIN__' is not defined